# Generated by Django 5.2.7 on 2025-11-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_appuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='credit_points_before',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='credit_points_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='use_credit_points',
            field=models.BooleanField(default=False),
        ),
    ]
