# Generated by Django 5.2.7 on 2025-11-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_order_credit_points_before_order_credit_points_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='customize',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
