# Generated by Django 5.2.7 on 2025-11-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_orderitem_customize_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='reset_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='reset_code_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
