# Generated by Django 5.2.7 on 2025-11-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_appuser_reset_code_appuser_reset_code_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='reset_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
