# Generated by Django 5.2.7 on 2025-11-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
