# Generated by Django 5.2.7 on 2025-11-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_menuitem_is_special'),
        ('menu', '0005_alter_menuitem_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='menu_items',
            field=models.ManyToManyField(blank=True, to='menu.menuitem'),
        ),
    ]
