# Generated by Django 5.2.7 on 2025-11-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_offer_menu_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='menu_items',
            field=models.ManyToManyField(blank=True, to='api.menuitem'),
        ),
    ]
