# Generated by Django 5.2.7 on 2025-10-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_order_type_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('dinein', 'Dine In'), ('delivery', 'Delivery')], default='pickup', max_length=50),
        ),
    ]
