# Generated by Django 5.2.7 on 2025-11-01 23:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menuitem_category_menuitem_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
