# Generated by Django 5.2.7 on 2025-11-21 02:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_menuitem_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'menu_category',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'managed': False},
        ),
    ]
