# Generated by Django 5.2.7 on 2025-11-23 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menucategory_alter_menuitem_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menuitem',
            table='menu_item',
        ),
    ]
